### ISSUE TITLE
Downlink issues

### ISSUE THREAD

**Issue by jithinsisaac** [MicrochipTech/atsamr34_lorawan_smart_meter#1]
Hey, the code works great with some tweaking for the WLR089U0 Xplained Pro. 

However, **downlink does not work**. Even after a downlink is schedued by the server, it is not processed by the node. 

It somehow does not enter the `if (LORAWAN_EVT_RX_DATA_AVAILABLE == appdata->evt)` statement in the `appdata_callback`  function in in `lorawan_app.c` file.

Would greatly appreciate some help on this. Thanks..

**Comment by gd91** [comment]
Hello, if required, raise a case to microchip.com/support for further support
